-- Disposable isolated database only; all synthetic records roll back.
begin;
create schema practice_test;
create function practice_test.ok(v boolean,label text) returns void language plpgsql as $$begin if v is distinct from true then raise exception 'FAIL: %',label;end if;raise notice 'PASS: %',label;end $$;
create function practice_test.denied(statement text,label text) returns void language plpgsql as $$begin begin execute statement;exception when others then raise notice 'PASS: %',label;return;end;raise exception 'FAIL: %',label;end $$;
grant usage on schema practice_test to authenticated,service_role;
grant execute on all functions in schema practice_test to authenticated,service_role;
select set_config('test.doctor',gen_random_uuid()::text,true),set_config('test.assistant',gen_random_uuid()::text,true),set_config('test.request',gen_random_uuid()::text,true);
insert into auth.users(id,email) values(current_setting('test.doctor')::uuid,'practice-doctor@example.invalid'),(current_setting('test.assistant')::uuid,'practice-assistant@example.invalid');
select carebridge_private.provision_staff(current_setting('test.doctor')::uuid,'Synthetic Doctor','doctor','SYNTHETIC');
select carebridge_private.provision_staff(current_setting('test.assistant')::uuid,'Synthetic Assistant','assistant');
select set_config('request.jwt.claim.sub',current_setting('test.doctor'),true);
set local role authenticated;
select carebridge.save_practice_settings(jsonb_build_object('chamber_enabled',true,'online_enabled',true,'chamber_fee',500,'online_fee',400,'slot_minutes',30,'visible_days',3,'notice_minutes',0,'max_daily',2,'paused',false,'advance_required',true,'weekly',jsonb_build_array(
 jsonb_build_object('type','chamber','weekday',extract(dow from (now() at time zone 'Asia/Dhaka')::date+1),'start','10:00','end','12:00','break_start','10:30','break_end','11:00'),
 jsonb_build_object('type','online','weekday',extract(dow from (now() at time zone 'Asia/Dhaka')::date+1),'start','14:00','end','15:00','break_start','','break_end',''))),
 '[{"provider":"bkash","enabled":true,"account_number":"01700000000","account_type":"merchant","instructions":"Synthetic only"},{"provider":"nagad","enabled":false,"account_number":"","account_type":"personal","instructions":""},{"provider":"rocket","enabled":false,"account_number":"","account_type":"merchant","instructions":""}]');
select practice_test.ok(carebridge.generate_practice_slots()=5,'Five slots respect weekly hours and break');
select practice_test.ok(carebridge.generate_practice_slots()=0,'Slot generation is duplicate-safe');
select set_config('test.slot',(select id::text from carebridge.appointment_slots where generation_key is not null order by starts_at limit 1),true);
select set_config('test.slot2',(select id::text from carebridge.appointment_slots where generation_key is not null order by starts_at offset 1 limit 1),true);
select practice_test.ok((select count(*)=5 from carebridge.appointment_slots),'No duplicate generated rows');
reset role;
select set_config('request.jwt.claim.sub','',true);
set local role service_role;
select practice_test.ok(jsonb_array_length(carebridge.public_booking_options()->'slots')=5,'Approved future availability published');
select practice_test.denied(format('select carebridge.submit_booking_v2(%L,''Synthetic Test'',''01700000001'',%L,''Test'',''test'',true,false,null)',gen_random_uuid(),current_setting('test.slot')),'Required payment cannot be omitted');
select set_config('test.appointment',carebridge.submit_booking_v2(current_setting('test.request')::uuid,'Synthetic Test','01700000001',current_setting('test.slot')::uuid,'Synthetic complaint','test',true,false,'{"provider":"bkash","sender":"01700000001","reference":"SYNTHETIC-CORE-001","amount":500}')::text,true);
select practice_test.ok(carebridge.submit_booking_v2(current_setting('test.request')::uuid,'Synthetic Test','01700000001',current_setting('test.slot')::uuid,'Synthetic complaint','test',true,false,'{"provider":"bkash","sender":"01700000001","reference":"SYNTHETIC-CORE-001","amount":500}')::text=current_setting('test.appointment'),'Paid booking retry is idempotent');
select practice_test.denied(format('select carebridge.submit_booking_v2(%L,''Duplicate Reference'',''01700000002'',%L,''Test'',''test'',true,false,''{"provider":"bkash","sender":"01700000002","reference":"SYNTHETIC-CORE-001","amount":500}'')',gen_random_uuid(),current_setting('test.slot2')),'Duplicate payment reference rejected atomically');
reset role;
-- Changes below are isolated fixture controls; no hosted data is touched.
update carebridge.practice_settings set max_daily=1;
select practice_test.ok(jsonb_array_length(carebridge.public_booking_options()->'slots')=0,'Daily limit includes pending appointments');
update carebridge.practice_settings set max_daily=2,paused=true;
select practice_test.ok(jsonb_array_length(carebridge.public_booking_options()->'slots')=0,'Pause hides all public slots');
update carebridge.practice_settings set paused=false,notice_minutes=10080;
select practice_test.ok(jsonb_array_length(carebridge.public_booking_options()->'slots')=0,'Minimum notice hides near-term slots');
update carebridge.practice_settings set notice_minutes=0,visible_days=1;
select practice_test.ok(jsonb_array_length(carebridge.public_booking_options()->'slots')=0,'Visible days use Bangladesh calendar boundaries');
update carebridge.practice_settings set visible_days=3;
select set_config('request.jwt.claim.sub',current_setting('test.doctor'),true);
set local role authenticated;
insert into carebridge.schedule_blocks(starts_at,ends_at,kind) select starts_at,ends_at,'blocked_date' from carebridge.appointment_slots where id=current_setting('test.slot2')::uuid;
reset role;
select practice_test.ok(jsonb_array_length(carebridge.public_booking_options()->'slots')=3,'Blocked time is removed from public availability');
select set_config('request.jwt.claim.sub',current_setting('test.assistant'),true);
set local role authenticated;
select practice_test.ok((select count(*)=1 from carebridge.patients),'Rejected booking leaves no orphan patient');
select practice_test.ok((select status='pending' and advance_required from carebridge.appointments where id=current_setting('test.appointment')::uuid),'Payment-required appointment starts pending');
select set_config('test.payment',(select id::text from carebridge.payments where appointment_id=current_setting('test.appointment')::uuid),true);
select practice_test.ok((select status='pending' from carebridge.payments where id=current_setting('test.payment')::uuid),'Payment evidence starts pending');
select practice_test.denied(format('select carebridge.change_appointment(%L,''confirmed'',''patient_request'')',current_setting('test.appointment')),'Cannot confirm before verifying required payment');
select practice_test.denied('select carebridge.generate_practice_slots()','Assistant cannot generate slots');
select practice_test.ok((select count(*)=0 from carebridge.payment_settings),'Assistant cannot read private payment settings');
select carebridge.review_payment_v2(current_setting('test.payment')::uuid,'verified','Synthetic merchant matched');
select practice_test.ok((select status='confirmed' from carebridge.appointments where id=current_setting('test.appointment')::uuid),'Payment approval confirms appointment transactionally');
select practice_test.denied(format('select carebridge.correct_payment(%L,false,''Synthetic reversal'')',current_setting('test.payment')),'Assistant cannot reverse payment');
reset role;
select set_config('request.jwt.claim.sub',current_setting('test.doctor'),true);
set local role authenticated;
select carebridge.correct_payment(current_setting('test.payment')::uuid,false,'Synthetic reversal');
select practice_test.ok((select status='pending' from carebridge.appointments where id=current_setting('test.appointment')::uuid),'Doctor reversal returns confirmed visit to pending');
select carebridge.correct_payment(current_setting('test.payment')::uuid,true,'Synthetic review correction');
select carebridge.review_payment_v2(current_setting('test.payment')::uuid,'verified','Rechecked merchant evidence');
select practice_test.ok((select count(*)=4 from carebridge.payment_events),'Payment decision history preserved');
select carebridge.change_appointment(current_setting('test.appointment')::uuid,'checked_in','attendance');
with c as(insert into carebridge.consultations(appointment_id,patient_id,chief_complaint) select id,patient_id,'Synthetic complaint' from carebridge.appointments where id=current_setting('test.appointment')::uuid returning id) select set_config('test.consultation',(select id::text from c),true);
select set_config('test.version',carebridge.create_prescription(current_setting('test.consultation')::uuid)::text,true);
select practice_test.ok(carebridge.create_prescription(current_setting('test.consultation')::uuid)::text=current_setting('test.version'),'Prescription creation is duplicate-safe');
select set_config('test.expected',(select updated_at::text from carebridge.prescription_versions where id=current_setting('test.version')::uuid),true);
select carebridge.save_practical_prescription(current_setting('test.version')::uuid,current_setting('test.expected')::timestamptz,'{"complaints":"Synthetic complaint","history":"History","allergy":"None recorded","examination":"Synthetic findings","diagnosis":"Synthetic diagnosis","investigations":"Test","advice":"Test","referral":"Synthetic referral","follow_up_date":"","medicines":[{"medicine_name":"Incomplete","strength":"","form":"","dose":"","frequency":"","duration":"","meal":"","notes":""}]}');
select practice_test.denied(format('select carebridge.finalize_prescription(%L)',current_setting('test.version')),'Incomplete autosaved draft cannot finalize');
select practice_test.denied(format('select carebridge.save_practical_prescription(%L,%L,''{"medicines":[]}'')',current_setting('test.version'),current_setting('test.expected')),'Stale draft rejected');
select set_config('test.expected',(select updated_at::text from carebridge.prescription_versions where id=current_setting('test.version')::uuid),true);
select carebridge.save_practical_prescription(current_setting('test.version')::uuid,current_setting('test.expected')::timestamptz,'{"complaints":"Synthetic complaint","history":"History","allergy":"None recorded","examination":"Synthetic findings","diagnosis":"Synthetic diagnosis","investigations":"Test","advice":"Test","referral":"Synthetic referral","follow_up_date":"","medicines":[{"medicine_name":"Synthetic medicine","strength":"10 mg","form":"Tablet","dose":"One","frequency":"Daily","duration":"3 days","meal":"after meals","notes":"Test only"}]}');
select practice_test.denied(format('select carebridge.finalize_practical_prescription(%L,%L)',current_setting('test.version'),current_setting('test.expected')),'Finalization rejects concurrent draft changes atomically');
select carebridge.finalize_practical_prescription(current_setting('test.version')::uuid,(select updated_at from carebridge.prescription_versions where id=current_setting('test.version')::uuid));
select set_config('test.root',(select prescription_id::text from carebridge.prescription_versions where id=current_setting('test.version')::uuid),true);
select set_config('test.revision',carebridge.revise_prescription(current_setting('test.root')::uuid)::text,true);
select practice_test.ok((select complaints='Synthetic complaint' and referral='Synthetic referral' and status='draft' from carebridge.prescription_versions where id=current_setting('test.revision')::uuid),'Revision retains practical clinical fields');
select practice_test.ok((select strength='10 mg' and dosage_form='Tablet' from carebridge.prescription_items where version_id=current_setting('test.revision')::uuid),'Revision retains structured medicine details');
select practice_test.denied(format('update carebridge.prescription_versions set diagnosis=''Changed'' where id=%L',current_setting('test.version')),'Finalized practical prescription remains immutable');
reset role;
select set_config('request.jwt.claim.sub',current_setting('test.assistant'),true);
set local role authenticated;
select practice_test.ok((select count(*)=0 from carebridge.prescription_versions),'Assistant cannot read practical prescriptions');
select practice_test.denied(format('select carebridge.save_practical_prescription(%L,now(),''{"medicines":[]}'')',current_setting('test.revision')),'Assistant cannot autosave prescriptions');
rollback;
