"use client";

import { FormEvent, useEffect, useState } from "react";
import { Activity, ArrowLeft, CalendarDays, CheckCircle2, ChevronRight, ClipboardList, Clock3, FileText, HeartPulse, LayoutDashboard, LockKeyhole, LogOut, Menu, MessageSquareText, Phone, Plus, Printer, Search, Send, Settings, ShieldCheck, Stethoscope, UserRound, UsersRound, Video, X } from "lucide-react";

type Role = "doctor" | "assistant";
type View = "home" | "booking" | "login" | "dashboard" | "patients" | "prescription" | "settings";
type Appointment = { id:string; patient:string; phone:string; age:string; gender:string; type:"Online"|"Chamber"; time:string; date:string; complaint:string; payment:string; status:"Pending"|"Confirmed"|"Completed" };

const seed:Appointment[]=[
 {id:"APT-1041",patient:"সাবিহা রহমান",phone:"01712-345678",age:"32",gender:"Female",type:"Chamber",time:"5:30 PM",date:"আজ",complaint:"জ্বর ও শরীর ব্যথা",payment:"Paid",status:"Confirmed"},
 {id:"APT-1042",patient:"মো. আরিফ হোসেন",phone:"01819-223344",age:"45",gender:"Male",type:"Online",time:"6:00 PM",date:"আজ",complaint:"ডায়াবেটিস ফলো-আপ",payment:"Verified",status:"Confirmed"},
 {id:"APT-1043",patient:"তানজিলা আক্তার",phone:"01610-998877",age:"27",gender:"Female",type:"Chamber",time:"6:30 PM",date:"আজ",complaint:"মাইগ্রেন",payment:"Verify",status:"Pending"}
];
const medicines=[{name:"Tab. Napa 500 mg",dose:"1+1+1",duration:"3 days",advice:"After meal"},{name:"Cap. Esomeprazole 20 mg",dose:"1+0+0",duration:"7 days",advice:"Before meal"}];

function Logo(){return <div className="brand"><span className="brand-mark"><HeartPulse size={23}/></span><span><b>CareBridge</b><small>Doctor Practice</small></span></div>}
function Toast({message,onClose}:{message:string;onClose:()=>void}){useEffect(()=>{const t=setTimeout(onClose,3200);return()=>clearTimeout(t)},[onClose]);return <div className="toast"><CheckCircle2 size={19}/><span>{message}</span></div>}

export default function Home(){
 const [view,setView]=useState<View>("home"),[role,setRole]=useState<Role|null>(null),[mobileOpen,setMobileOpen]=useState(false),[appointments,setAppointments]=useState<Appointment[]>(()=>{if(typeof window==="undefined")return seed;const raw=localStorage.getItem("carebridge-appointments");if(raw)try{return JSON.parse(raw)}catch{}return seed}),[toast,setToast]=useState("");
 useEffect(()=>{if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{})},[]);
 useEffect(()=>localStorage.setItem("carebridge-appointments",JSON.stringify(appointments)),[appointments]);
 const go=(v:View)=>{setView(v);setMobileOpen(false);scrollTo({top:0,behavior:"smooth"})};
 const login=(r:Role)=>{setRole(r);go("dashboard");setToast(`${r==="doctor"?"Doctor":"Assistant"} demo account-এ লগইন হয়েছে`)};
 const add=(a:Appointment)=>{setAppointments(p=>[a,...p]);setToast("Appointment request গ্রহণ করা হয়েছে; SMS queue-তে যোগ হয়েছে");go("home")};
 const update=(id:string,status:Appointment["status"])=>{setAppointments(p=>p.map(a=>a.id===id?{...a,status,payment:"Verified"}:a));setToast("Appointment confirmed — demo SMS পাঠানো হয়েছে")};
 if(view==="booking")return <Booking onBack={()=>go("home")} onSubmit={add}/>;
 if(view==="login")return <Login onBack={()=>go("home")} onLogin={login}/>;
 if(role&&["dashboard","patients","prescription","settings"].includes(view))return <AppShell {...{role,view,go,mobileOpen,setMobileOpen,appointments,update,toast,setToast}} logout={()=>{setRole(null);go("home")}}/>;
 return <Landing onBook={()=>go("booking")} onLogin={()=>go("login")} toast={toast} setToast={setToast}/>;
}

function Landing({onBook,onLogin,toast,setToast}:{onBook:()=>void;onLogin:()=>void;toast:string;setToast:(s:string)=>void}){return <div className="site-shell">
 <header className="public-nav"><Logo/><nav><a href="#services">সেবা</a><a href="#schedule">সময়সূচি</a><a href="#about">ডাক্তার সম্পর্কে</a></nav><div className="nav-actions"><button className="btn ghost" onClick={onLogin}><LockKeyhole size={16}/> Staff login</button><button className="btn primary" onClick={onBook}>অ্যাপয়েন্টমেন্ট নিন</button></div></header>
 <main><section className="hero"><div className="hero-copy"><span className="eyebrow"><span/> অনলাইন ও চেম্বার কনসালটেশন</span><h1>বিশ্বস্ত চিকিৎসা,<br/><em>আপনার সুবিধামতো।</em></h1><p>ঘরে বসে অথবা সরাসরি চেম্বারে চিকিৎসকের পরামর্শ নিন। সহজ অ্যাপয়েন্টমেন্ট, নিরাপদ রোগী রেকর্ড ও ডিজিটাল প্রেসক্রিপশন—এক জায়গায়।</p><div className="hero-actions"><button className="btn primary large" onClick={onBook}><CalendarDays/> অ্যাপয়েন্টমেন্ট নিন</button><a className="btn outline large" href="tel:+8801700000000"><Phone/> কল করুন</a></div><div className="trust-row"><span><ShieldCheck/> তথ্য সুরক্ষিত</span><span><Clock3/> সময়মতো পরামর্শ</span><span><FileText/> ডিজিটাল প্রেসক্রিপশন</span></div></div>
 <div className="doctor-stage"><div className="stage-orbit orbit-one"/><div className="stage-orbit orbit-two"/><div className="doctor-card"><div className="doctor-avatar"><Stethoscope size={76}/><span className="online-dot"/></div><div><span className="available">আজ অ্যাপয়েন্টমেন্ট আছে</span><h2>Dr. Arif Hasan</h2><p>MBBS, FCPS (Medicine)</p><p className="muted">Consultant Physician</p></div><div className="doctor-stats"><span><b>12+</b><small>Years</small></span><span><b>8k+</b><small>Patients</small></span><span><b>4.9</b><small>Rating</small></span></div></div><div className="float-card video-float"><Video/><span><b>Online consultation</b><small>Google Meet / Zoom</small></span></div><div className="float-card next-float"><CalendarDays/><span><small>Next available</small><b>আজ, ৫:৩০ PM</b></span></div></div></section>
 <section className="quick-book"><div><small>CONSULTATION TYPE</small><b><Video/> Online consultation</b></div><div><small>NEXT AVAILABLE</small><b><CalendarDays/> আজ, ৫:৩০ PM</b></div><div><small>CONSULTATION FEE</small><b>৳ 800</b></div><button className="btn dark" onClick={onBook}>সময় নির্বাচন করুন <ChevronRight/></button></section>
 <section id="services" className="section"><div className="section-heading"><span>চিকিৎসাসেবা</span><h2>পরিপূর্ণ মেডিসিন কেয়ার</h2><p>প্রাথমিক মূল্যায়ন থেকে নিয়মিত ফলো-আপ—প্রয়োজন অনুযায়ী অনলাইন বা চেম্বারে।</p></div><div className="service-grid">{[[Activity,"সাধারণ মেডিসিন","জ্বর, সর্দি-কাশি, দুর্বলতা ও সাধারণ শারীরিক সমস্যার পরামর্শ।"],[HeartPulse,"দীর্ঘমেয়াদি রোগ","ডায়াবেটিস, উচ্চ রক্তচাপ ও অন্যান্য দীর্ঘমেয়াদি রোগের ফলো-আপ।"],[Video,"অনলাইন পরামর্শ","Google Meet, Zoom অথবা WhatsApp-এর মাধ্যমে নির্ধারিত সময়ে পরামর্শ।"],[ClipboardList,"ডিজিটাল প্রেসক্রিপশন","পরামর্শ শেষে যাচাইযোগ্য ডিজিটাল প্রেসক্রিপশন ডাউনলোড করুন।"]].map(([I,t,d],i)=>{const Icon=I as typeof Activity;return <article className="service-card" key={i}><span className="icon-box"><Icon/></span><h3>{t as string}</h3><p>{d as string}</p></article>})}</div></section>
 <section id="schedule" className="section schedule"><div><span className="section-kicker">সহজ অ্যাপয়েন্টমেন্ট</span><h2>তিন ধাপে চিকিৎসকের পরামর্শ নিন</h2><div className="steps">{[["01","সময় নির্বাচন","অনলাইন বা চেম্বার, সুবিধাজনক সময় বেছে নিন।"],["02","তথ্য ও পেমেন্ট","প্রাথমিক তথ্য ও payment transaction ID দিন।"],["03","কনসালটেশন","Confirmation SMS পেয়ে নির্ধারিত সময়ে পরামর্শ নিন।"]].map(s=><div className="step" key={s[0]}><b>{s[0]}</b><span><h3>{s[1]}</h3><p>{s[2]}</p></span></div>)}</div></div><div className="availability-card"><div className="calendar-top"><span><CalendarDays/> সেপ্টেম্বর ২০২৬</span><button>আজ</button></div><div className="calendar-grid">{["রবি","সোম","মঙ্গল","বুধ","বৃহ","শুক্র","শনি"].map(d=><small key={d}>{d}</small>)}{Array.from({length:21},(_,i)=><button className={[7,9,12,14,16].includes(i+1)?"active-day":""} key={i}>{i+1}</button>)}</div><div className="slots"><span>Available time</span><div><button>5:30 PM</button><button>6:00 PM</button><button>7:30 PM</button></div></div><button className="btn primary full" onClick={onBook}>অ্যাপয়েন্টমেন্ট নিন</button></div></section>
 <section id="about" className="cta"><div><span>আপনার স্বাস্থ্য, আপনার সময়</span><h2>আজই পরামর্শের সময় নির্ধারণ করুন</h2><p>জরুরি বা জীবন-সংশয়ী অবস্থায় অনলাইন অ্যাপয়েন্টমেন্টের অপেক্ষা না করে নিকটস্থ হাসপাতালের জরুরি বিভাগে যোগাযোগ করুন।</p></div><button className="btn white large" onClick={onBook}>সময় নির্বাচন করুন <ChevronRight/></button></section></main>
 <footer><Logo/><p>© 2026 CareBridge Doctor Practice · Demo application</p><button className="link-btn" onClick={onLogin}>Staff access</button></footer>{toast&&<Toast message={toast} onClose={()=>setToast("")}/>}</div>}

function Booking({onBack,onSubmit}:{onBack:()=>void;onSubmit:(a:Appointment)=>void}){
 const [step,setStep]=useState(1),[type,setType]=useState<"Online"|"Chamber">("Online"),[date,setDate]=useState("2026-09-16"),[time,setTime]=useState("5:30 PM"),[p,setP]=useState({name:"",phone:"",age:"",gender:"Male",complaint:"",payment:"bKash",trx:""});
 const submit=(e:FormEvent)=>{e.preventDefault();if(!p.name||!p.phone||!p.complaint)return;onSubmit({id:`APT-${1040+Math.floor(Math.random()*800)}`,patient:p.name,phone:p.phone,age:p.age,gender:p.gender,type,time,date,complaint:p.complaint,payment:"Verify",status:"Pending"})};
 return <div className="flow-page"><header className="flow-header"><button className="icon-button" onClick={onBack}><ArrowLeft/></button><Logo/><span className="demo-pill">LOCAL DEMO</span></header><main className="booking-wrap"><div className="flow-title"><span>অ্যাপয়েন্টমেন্ট বুকিং</span><h1>আপনার সুবিধাজনক সময় বেছে নিন</h1><p>পেমেন্ট যাচাইয়ের পর SMS-এ নিশ্চিতকরণ পাঠানো হবে।</p></div><div className="stepper">{[1,2,3].map(n=><div className={step>=n?"done":""} key={n}><b>{step>n?"✓":n}</b><span>{n===1?"সময়":n===2?"তথ্য":"পেমেন্ট"}</span></div>)}</div><form className="booking-card" onSubmit={submit}>
 {step===1&&<><h2>কনসালটেশনের ধরন</h2><div className="choice-grid"><button type="button" className={type==="Online"?"choice selected":"choice"} onClick={()=>setType("Online")}><Video/><b>অনলাইন কনসালটেশন</b><small>Google Meet / Zoom / WhatsApp</small><span>৳ 800</span></button><button type="button" className={type==="Chamber"?"choice selected":"choice"} onClick={()=>setType("Chamber")}><Stethoscope/><b>চেম্বার কনসালটেশন</b><small>সরাসরি চেম্বারে উপস্থিত হয়ে</small><span>৳ 1,000</span></button></div><div className="form-grid"><label>তারিখ<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>সময়<select value={time} onChange={e=>setTime(e.target.value)}><option>5:30 PM</option><option>6:00 PM</option><option>6:30 PM</option><option>7:30 PM</option></select></label></div><button type="button" className="btn primary full" onClick={()=>setStep(2)}>পরবর্তী ধাপ <ChevronRight/></button></>}
 {step===2&&<><h2>রোগীর তথ্য</h2><div className="form-grid"><label>রোগীর নাম *<input required placeholder="পূর্ণ নাম" value={p.name} onChange={e=>setP({...p,name:e.target.value})}/></label><label>মোবাইল নম্বর *<input required placeholder="01XXXXXXXXX" value={p.phone} onChange={e=>setP({...p,phone:e.target.value})}/></label><label>বয়স<input type="number" placeholder="বছর" value={p.age} onChange={e=>setP({...p,age:e.target.value})}/></label><label>লিঙ্গ<select value={p.gender} onChange={e=>setP({...p,gender:e.target.value})}><option>Male</option><option>Female</option><option>Other</option></select></label><label className="wide">প্রধান সমস্যা *<textarea required placeholder="সমস্যা সংক্ষেপে লিখুন" value={p.complaint} onChange={e=>setP({...p,complaint:e.target.value})}/></label></div><div className="flow-buttons"><button type="button" className="btn outline" onClick={()=>setStep(1)}>পেছনে</button><button type="button" className="btn primary" onClick={()=>p.name&&p.phone&&p.complaint&&setStep(3)}>পরবর্তী ধাপ <ChevronRight/></button></div></>}
 {step===3&&<><h2>পেমেন্টের তথ্য</h2><div className="payment-note"><MessageSquareText/><div><b>Demo payment verification</b><p>নিচের নম্বরে Send Money করে transaction ID দিন। Live version-এ প্রকৃত merchant number বসবে।</p></div></div><div className="pay-methods">{["bKash","Nagad","Rocket"].map(x=><button type="button" className={p.payment===x?"selected":""} onClick={()=>setP({...p,payment:x})} key={x}>{x}</button>)}</div><div className="merchant-box"><small>{p.payment} payment number</small><b>01700-000000</b><span>Amount: ৳ {type==="Online"?"800":"1,000"}</span></div><label>Transaction ID *<input required placeholder="যেমন: 9AB12CD34" value={p.trx} onChange={e=>setP({...p,trx:e.target.value})}/></label><label className="consent"><input type="checkbox" required/> আমি প্রদত্ত তথ্য সঠিক এবং teleconsultation-এর সীমাবদ্ধতা বুঝেছি।</label><div className="flow-buttons"><button type="button" className="btn outline" onClick={()=>setStep(2)}>পেছনে</button><button className="btn primary" type="submit"><CheckCircle2/> বুকিং সম্পন্ন করুন</button></div></>}
 </form></main></div>}

function Login({onBack,onLogin}:{onBack:()=>void;onLogin:(r:Role)=>void}){const [role,setRole]=useState<Role>("doctor");return <div className="login-page"><button className="back-link" onClick={onBack}><ArrowLeft/> হোমে ফিরুন</button><div className="login-panel"><Logo/><div className="login-icon"><LockKeyhole/></div><span>STAFF PORTAL</span><h1>স্বাগতম</h1><p>Local demo account নির্বাচন করে dashboard পরীক্ষা করুন।</p><div className="role-tabs"><button className={role==="doctor"?"active":""} onClick={()=>setRole("doctor")}><Stethoscope/> Doctor</button><button className={role==="assistant"?"active":""} onClick={()=>setRole("assistant")}><UserRound/> Assistant</button></div><label>Email<input value={role==="doctor"?"doctor@demo.local":"assistant@demo.local"} readOnly/></label><label>Password<input type="password" value="demopass" readOnly/></label><button className="btn primary full large" onClick={()=>onLogin(role)}>Demo account-এ প্রবেশ করুন</button><small className="secure-note"><ShieldCheck/> Local demo—real patient data ব্যবহার করবেন না।</small></div><aside className="login-art"><div><HeartPulse/><h2>Patient care,<br/>organized beautifully.</h2><p>Appointments, consultations, prescriptions and follow-ups—one calm workspace.</p></div></aside></div>}

function AppShell({role,view,go,logout,mobileOpen,setMobileOpen,appointments,update,toast,setToast}:{role:Role;view:View;go:(v:View)=>void;logout:()=>void;mobileOpen:boolean;setMobileOpen:(v:boolean)=>void;appointments:Appointment[];update:(id:string,s:Appointment["status"])=>void;toast:string;setToast:(s:string)=>void}){
 const nav:[[View,typeof LayoutDashboard,string],[View,typeof LayoutDashboard,string],[View,typeof LayoutDashboard,string],[View,typeof LayoutDashboard,string]]=[["dashboard",LayoutDashboard,"Dashboard"],["patients",UsersRound,"Patients"],["prescription",FileText,"Prescription"],["settings",Settings,"Settings"]];
 return <div className="app-layout"><aside className={mobileOpen?"app-sidebar open":"app-sidebar"}><div className="sidebar-head"><Logo/><button className="close-menu" onClick={()=>setMobileOpen(false)}><X/></button></div><nav>{nav.map(([v,I,t])=><button key={v} className={view===v?"active":""} onClick={()=>go(v)}><I/>{t}</button>)}</nav><div className="role-box"><span className="avatar-small">{role==="doctor"?"DA":"AS"}</span><div><b>{role==="doctor"?"Dr. Arif Hasan":"Nadia Akter"}</b><small>{role==="doctor"?"Doctor / Admin":"Assistant"}</small></div></div><button className="logout" onClick={logout}><LogOut/> Log out</button></aside><div className="app-main"><header className="app-topbar"><button className="menu-button" onClick={()=>setMobileOpen(true)}><Menu/></button><div><b>{view==="dashboard"?"Practice overview":view==="patients"?"Patient records":view==="prescription"?"Prescription builder":"Practice settings"}</b><small>Sunday, 13 September 2026</small></div><div className="top-actions"><span className="demo-pill">LOCAL DEMO</span><button className="btn primary" onClick={()=>go("home")}>Public page</button></div></header><main className="app-content">{view==="dashboard"&&<Dashboard {...{role,appointments,update}}/>}{view==="patients"&&<Patients appointments={appointments}/>} {view==="prescription"&&<Prescription role={role} notify={setToast}/>} {view==="settings"&&<AppSettings role={role} notify={setToast}/>}</main></div>{toast&&<Toast message={toast} onClose={()=>setToast("")}/>}</div>}

function Dashboard({role,appointments,update}:{role:Role;appointments:Appointment[];update:(id:string,s:Appointment["status"])=>void}){const confirmed=appointments.filter(a=>a.status==="Confirmed").length;return <><div className="welcome-row"><div><span>Good evening</span><h1>{role==="doctor"?"Dr. Arif Hasan":"Nadia Akter"}</h1><p>আজকের patient queue ও pending কাজ এক নজরে দেখুন।</p></div><button className="btn primary"><Plus/> Walk-in patient</button></div><div className="stat-grid">{[[CalendarDays,"আজকের appointment",appointments.length,"+2 from yesterday"],[CheckCircle2,"Confirmed",confirmed,"Ready for consultation"],[Clock3,"Pending verification",appointments.filter(a=>a.status==="Pending").length,"Needs attention"],[MessageSquareText,"SMS sent",appointments.length*2,"Demo delivery log"]].map(([I,t,n,d],i)=>{const Icon=I as typeof Activity;return <article className="stat-card" key={i}><span><Icon/></span><div><small>{t as string}</small><b>{n as number}</b><p>{d as string}</p></div></article>})}</div><section className="panel"><div className="panel-head"><div><h2>আজকের appointments</h2><p>সময় অনুযায়ী patient queue</p></div><button className="btn ghost"><Search/> Search</button></div><div className="appointment-list">{appointments.map(a=><article key={a.id}><div className="time-col"><b>{a.time}</b><small>{a.type}</small></div><span className="patient-avatar">{a.patient.slice(0,1)}</span><div className="patient-info"><b>{a.patient}</b><small>{a.age} yrs · {a.gender} · {a.id}</small><p>{a.complaint}</p></div><span className={`status ${a.status.toLowerCase()}`}>{a.status}</span><div className="row-actions">{a.status==="Pending"&&<button onClick={()=>update(a.id,"Confirmed")}>Confirm & SMS</button>}<button>Details</button></div></article>)}</div></section><div className="dashboard-lower"><section className="panel"><div className="panel-head"><div><h2>Quick actions</h2><p>Frequently used tools</p></div></div><div className="quick-actions">{[[FileText,"New prescription"],[UsersRound,"Find patient"],[Send,"Send reminder"],[CalendarDays,"Manage schedule"]].map(([I,t],i)=>{const Icon=I as typeof Activity;return <button key={i}><Icon/><span>{t as string}</span><ChevronRight/></button>})}</div></section><section className="panel activity-panel"><div className="panel-head"><div><h2>Recent activity</h2><p>Demo audit trail</p></div></div>{["Appointment APT-1042 confirmed","Prescription RX-2026-089 created","SMS reminder delivered"].map((t,i)=><div className="activity-item" key={t}><span/><div><b>{t}</b><small>{i+1} hour ago</small></div></div>)}</section></div></>}

function Patients({appointments}:{appointments:Appointment[]}){return <section className="panel"><div className="panel-head"><div><h2>Patient directory</h2><p>Local demo patient records</p></div><button className="btn primary"><Plus/> Add patient</button></div><div className="searchbox"><Search/><input placeholder="নাম, মোবাইল বা patient ID দিয়ে খুঁজুন"/></div><div className="data-table"><div className="table-row table-header"><span>Patient</span><span>Contact</span><span>Last complaint</span><span>Visit type</span><span>Status</span></div>{appointments.map(a=><div className="table-row" key={a.id}><span><b>{a.patient}</b><small>{a.id} · {a.age} yrs</small></span><span>{a.phone}</span><span>{a.complaint}</span><span>{a.type}</span><span className={`status ${a.status.toLowerCase()}`}>{a.status}</span></div>)}</div></section>}

function Prescription({role,notify}:{role:Role;notify:(s:string)=>void}){const [items,setItems]=useState(medicines),[patient,setPatient]=useState("সাবিহা রহমান"),canEdit=role==="doctor";return <div className="rx-layout"><section className="panel rx-form"><div className="panel-head"><div><h2>Prescription builder</h2><p>{canEdit?"Clinical information পূরণ করে preview করুন":"Assistant prescription edit করতে পারে না"}</p></div><span className="status confirmed">DRAFT</span></div><fieldset disabled={!canEdit}><div className="form-grid"><label>Patient<select value={patient} onChange={e=>setPatient(e.target.value)}><option>সাবিহা রহমান</option><option>মো. আরিফ হোসেন</option></select></label><label>Date<input type="date" value="2026-09-13" readOnly/></label><label className="wide">Chief complaint<textarea defaultValue="জ্বর ও শরীর ব্যথা ৩ দিন ধরে"/></label><label className="wide">Clinical findings<textarea defaultValue="Temp 101°F, BP 120/80 mmHg. No respiratory distress."/></label><label>Diagnosis<input defaultValue="Acute febrile illness"/></label><label>Investigation<input defaultValue="CBC, Dengue NS1 (if indicated)"/></label></div><h3 className="subhead">Rx / Medicines</h3>{items.map((m,i)=><div className="medicine-row" key={i}><input value={m.name} onChange={e=>setItems(items.map((x,j)=>j===i?{...x,name:e.target.value}:x))}/><input defaultValue={m.dose}/><input defaultValue={m.duration}/><input defaultValue={m.advice}/><button type="button" onClick={()=>setItems(items.filter((_,j)=>j!==i))}><X/></button></div>)}<button type="button" className="btn outline" onClick={()=>setItems([...items,{name:"",dose:"",duration:"",advice:""}])}><Plus/> Add medicine</button><label className="wide advice-label">Advice<textarea defaultValue="পর্যাপ্ত পানি পান করুন। অবস্থা খারাপ হলে জরুরি বিভাগে যোগাযোগ করুন।"/></label></fieldset><div className="rx-buttons"><button className="btn outline" onClick={()=>window.print()}><Printer/> Print preview</button><button className="btn primary" disabled={!canEdit} onClick={()=>notify("Prescription সংরক্ষিত হয়েছে এবং demo SMS পাঠানো হয়েছে")}><Send/> Save & notify</button></div></section><PrescriptionPreview patient={patient} items={items}/></div>}

function PrescriptionPreview({patient,items}:{patient:string;items:typeof medicines}){return <aside className="rx-paper"><div className="rx-letterhead"><span><HeartPulse/></span><div><h2>Dr. Arif Hasan</h2><p>MBBS, FCPS (Medicine)</p><small>Consultant Physician · BMDC Reg: A-00000</small></div></div><div className="rx-meta"><span><b>Patient</b>{patient}, 32 years</span><span><b>Date</b>13 Sep 2026</span><span><b>Rx ID</b>RX-2026-091</span></div><div className="rx-body"><p><b>Diagnosis:</b> Acute febrile illness</p><h1>℞</h1>{items.map((m,i)=><div className="rx-item" key={i}><b>{i+1}. {m.name}</b><span>{m.dose} · {m.duration}</span><small>{m.advice}</small></div>)}<div className="rx-advice"><b>Advice</b><p>পর্যাপ্ত পানি পান করুন। অবস্থা খারাপ হলে জরুরি বিভাগে যোগাযোগ করুন।</p></div></div><div className="rx-sign"><span>Digitally verified</span><div>Doctor&apos;s signature</div></div><footer><small>CareBridge Clinic · Dhaka · Hotline: 01700-000000</small></footer></aside>}

function AppSettings({role,notify}:{role:Role;notify:(s:string)=>void}){return <div className="settings-grid"><section className="panel"><div className="panel-head"><div><h2>Practice settings</h2><p>Demo configuration</p></div></div>{[["SMS provider","Mock SMS is active","DEMO"],["Supabase connection","Local storage mode is active","LOCAL"],["Temporary file retention","Patient uploads expire","7 days"],["Your access","Role-based permissions",role]].map(x=><div className="setting-line" key={x[0]}><div><b>{x[0]}</b><small>{x[1]}</small></div><b>{x[2]}</b></div>)}<button className="btn primary" onClick={()=>notify("Demo settings সংরক্ষিত হয়েছে")}>Save settings</button></section><section className="panel"><div className="panel-head"><div><h2>Live setup checklist</h2><p>Deploy করার আগে প্রয়োজন হবে</p></div></div><ul className="checklist"><li><CheckCircle2/> Supabase URL ও anon key</li><li><CheckCircle2/> Database SQL চালানো</li><li><CheckCircle2/> SMS API credentials</li><li><CheckCircle2/> Doctor profile ও BMDC information</li><li><CheckCircle2/> Merchant payment number</li></ul></section></div>}
